;;; minor-mode-hack-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from minor-mode-hack.el

(autoload 'raise-minor-mode-map-alist "minor-mode-hack" "\
Raise `minor-mode-map-alist' priority of MODE-SYMBOL.

(fn MODE-SYMBOL)")
(autoload 'lower-minor-mode-map-alist "minor-mode-hack" "\
Lower `minor-mode-map-alist' priority of MODE-SYMBOL.

(fn MODE-SYMBOL)")
(autoload 'show-minor-mode-map-priority "minor-mode-hack" "\
Show priority of `minor-mode-map-alist'." t)
(register-definition-prefixes "minor-mode-hack" '("minor-mode-hack-version"))

;;; End of scraped data

(provide 'minor-mode-hack-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; minor-mode-hack-autoloads.el ends here
