;;; color-moccur-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from color-moccur.el

(autoload 'occur-by-moccur "color-moccur" "\
Use this instead of occur.
Argument REGEXP regexp.
Argument ARG whether buffers which is not related to files are searched.

(fn REGEXP ARG)" t)
(autoload 'moccur-grep-find "color-moccur" "\


(fn DIR INPUTS)" t)
(autoload 'dired-do-moccur "color-moccur" "\
Show all lines of all buffers containing a match for REGEXP.
The lines are shown in a buffer named *Moccur*.
It serves as a menu to find any of the occurrences in this buffer.
\\[describe-mode] in that buffer will explain how.

(fn REGEXP ARG)" t)
(autoload 'grep-buffers "color-moccur" "\
*Run `grep` PROGRAM to match EXPRESSION (with optional OPTIONS) on all visited files." t)
(autoload 'search-buffers "color-moccur" "\
*Search string of all buffers.

(fn REGEXP ARG)" t)
(register-definition-prefixes "color-moccur" '("*moccur-buffer-name-" "Buffer-menu-moccur" "buffer-menu-moccur" "clean-dmoccur-buffers" "color-moccur-default-ime-status" "dired-do-moccur-by-m" "dmoccur" "isearch-moccur" "kill-buffer-after-dired-do-moccur" "moccur" "search-buffers-" "string>"))

;;; End of scraped data

(provide 'color-moccur-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; color-moccur-autoloads.el ends here
